# -*- coding: utf-8 -*-
"""airbnb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/137_wWiWpKlPWRsXRhGBBImq6tLVHDiRn

# `ANÁLISE DE DADOS AIRBNB`
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/AB_NYC_2019.csv')

df.head(3)

"""# 1.Qual o preço médio de todos os valores da cidade de Nova York?"""

price_Aluguel = df.loc[:, 'price']

media_Aluguel = np.mean(price_Aluguel)

print("A média dos aluguéis é:", media_Aluguel.round(2))

"""# 2.Qual os nomes distintos de todos os valores dos aluguéis da cidade de Nova York?"""

name_City = df.loc[:, 'neighbourhood_group'].unique()

print(name_City)

"""# 3.Qual o valor máximo da coluna que contém todos os valores dos aluguéis?"""

price_Max = df.loc[:, 'price'].max()

print(price_Max)

"""# 4.Quais são as categorias de imóveis que estão cadastrados dentro da base de dados da cidade de Nova York?

"""

room_Types = df.loc[:, 'room_type'].unique()

print(room_Types)

"""# 5.Quantos usuários/host únicos estão cadastrados na base de dados da cidade de Nova York?"""

hosts_Unico = df.loc[:,'host_id'].unique()

print(len(hosts_Unico))

"""# 6.Qual o desvio padrão em torno da média dos preços dos imóveis?"""

price = df.loc[:, 'price']

desvio_Padrao = np.std(price)

mean_Price = np.mean(price)

print(f"O desvio padrão é de: {desvio_Padrao:.2f}")

print(f"A média de preços é de: {mean_Price:.2f}")

#var =  df.loc[:, 'price'].std()

"""# 7.Existem aluguéis mais baratos ou caros?"""

from matplotlib import pyplot as plt

prices = df.loc[:, 'price'] < 1000

new_prices = df.loc[prices, 'price']

print(f'O maior valor do aluguel é de: {np.max(new_prices)}\n')
print(f'O menor valor do aluguel é de: {np.min(new_prices)}\n')

plt.hist(new_prices, bins=(11))#(1000 - 0) / 100

"""# 8.Qual a distribuição do número de Reviews? Existem imóveis com muitos Reviews e outros com poucos?"""

reviews = df.loc[:, 'number_of_reviews'] < 300

new_reviews = df.loc[reviews, 'number_of_reviews']

plt.hist(new_reviews, bins=30)

"""# 9.Qual distribuição dos imóveis de acordo com o número mínimo de pernoites que podem ser agendados?"""

pernoite = df.loc[:,'minimum_nights'] < 100

pernoites = df.loc[pernoite, 'minimum_nights']

plt.hist(pernoites, bins=20);

"""# 10.Qual a média e a mediana de imóveis cadastrados por host?"""

hosts = df.loc[:, 'calculated_host_listings_count']

print(f'{np.mean(hosts):.2f}')

print(np.median(hosts))

"""# 11.Qual a data mais recente da última avaliação?"""

data = df.loc[:, 'last_review'].sort_values(ascending = True)

print(f'A data mais recente é {data.loc[317]}')

"""# 12.Qual o valor máximo de pernoites agendadas?"""

pernoites_max = df.loc[:, 'minimum_nights'].sort_values(ascending = False)

print(pernoites_max.loc[5767])