# -*- coding: utf-8 -*-
"""analise-geo-airbnb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vm4ff1ggaBFL9Lj1LCK6Tz8wWu08GjGX

# **ANÁLISE DE DADOS GEOGRÁFICA AIRBNB**
"""

import pandas as pd
import plotly.express as px
import folium

df = pd.read_csv('/content/AB_NYC_2019.csv')
df.head(1)

"""# Qual é o valor do aluguel (DIÁRIO) mais caro de cada região da base de dados da cidade de Nova York?"""

df_plot = df.loc[:, ['neighbourhood_group', 'price'] ].groupby(['neighbourhood_group']).max().reset_index()

px.bar( df_plot, x='neighbourhood_group', y='price')

"""# Onde estão localizados os imóveis com os valores dos aluguéis mais caros da cidade de Nova York?"""

maps = df.loc[:, [ 'neighbourhood_group', 'price', 'latitude', 'longitude' ] ].groupby(['neighbourhood_group']).max().reset_index()

print(maps)

image_folium = folium.Figure( width=1024, height=768 )

local_geo = folium.Map(
    location=[maps.loc[:, 'latitude'].mean(),
              maps.loc[:, 'longitude'].mean()],
              zoom_start=14,
              control_scale=True
)

for index, location in maps.iterrows():
  folium.Marker( [location['latitude'],
                  location['longitude']],
                  popup=location['neighbourhood_group'] ).add_to(local_geo)

local_geo